build: false

environment:
    PYTHON: "C:\\Python27"
    PYTHON_VERSION: "2.7.8"
    PYTHON_ARCH: "32"

    CONAN_REFERENCE: "mingw_installer/1.0"
    CONAN_USERNAME: "conan"
    CONAN_LOGIN_USERNAME: "lasote"
    CONAN_CHANNEL: "testing"
    CONAN_UPLOAD: "https://api.bintray.com/conan/conan-community/conan"
    CONAN_STABLE_BRANCH_PATTERN: "master"
    CONAN_UPLOAD_ONLY_WHEN_STABLE: 1
    CONAN_TOTAL_PAGES: 4

    matrix:
        - CONAN_CURRENT_PAGE: 1
        - CONAN_CURRENT_PAGE: 2
        - CONAN_CURRENT_PAGE: 3
        - CONAN_CURRENT_PAGE: 4

install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan --upgrade
  - pip.exe install git+https://github.com/anton-matosov/conan-package-tools.git@mingw --upgrade
  - conan user # It creates the conan data directory

test_script:
  - python build.py
