build: false

environment:
    PYTHON: "C:\\Python27"
    PYTHON_VERSION: "2.7.8"
    PYTHON_ARCH: "32"

    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    CONAN_VISUAL_VERSIONS: 14
    CONAN_REFERENCE: "mingw-installer/0.1"
    CONAN_UPLOAD: "https://api.bintray.com/conan/anton-matosov/general"
    CONAN_USERNAME: "anton-matosov"
    CONAN_LOGIN_USERNAME: "anton-matosov"
    CONAN_CHANNEL: "testing"
    CONAN_STABLE_BRANCH_PATTERN: "release/*"
    VS150COMNTOOLS: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\Common7\\Tools\\"
    CONAN_TOTAL_PAGES: 10
    
    matrix:
        - CONAN_CURRENT_PAGE: 1
        - CONAN_CURRENT_PAGE: 2
        - CONAN_CURRENT_PAGE: 3
        - CONAN_CURRENT_PAGE: 4
        - CONAN_CURRENT_PAGE: 5
        - CONAN_CURRENT_PAGE: 6
        - CONAN_CURRENT_PAGE: 7
        - CONAN_CURRENT_PAGE: 8
        - CONAN_CURRENT_PAGE: 9
        - CONAN_CURRENT_PAGE: 10

install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install git+https://github.com/anton-matosov/conan.git --upgrade
  - pip.exe install git+https://github.com/conan-io/conan-package-tools.git
  - conan user # It creates the conan data directory

test_script:
  - python build.py
